version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smart-home-rabbit
    ports:
      - "5672:5672"     # RabbitMQ broker
      - "15672:15672"   # RabbitMQ web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: smart-home-app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
